version: 2
updates:
  - package-ecosystem: "npm"          # Identifica o ecossistema (Node.js/npm)
    directory: "/"                      # Indica que o package.json está na raiz
    schedule:                           # Define a frequência
      interval: "weekly"                # Executa semanalmente
      day: "monday"                     # Dia específico da semana
      time: "09:00"                   # Hora específica
      timezone: "America/Sao_Paulo"     # Fuso horário
    open-pull-requests-limit: 10        # Limita o número de PRs abertos simultaneamente
    
    # IMPORTANTE: Troque "seu_usuario" pelo seu login do GitHub
    reviewers:                          
      - "morpheusbr"
    assignees:                          
      - "morpheusbr"
      
    labels:                             
      - "dependencies"                  

    groups:
      # Grupo 1: Agrupa todas as atualizações de pacotes de desenvolvimento (devDependencies)
      development:
        dependency-type: "development"
        update-types:
          - "major"
          - "minor"
          - "patch"

      # Grupo 2: Agrupa o restante (dependencies) que não caiu no grupo acima
      dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
